// vue-component-demo/components/lib/demo/src/main.vue
<!--
 * @Author: 郁南
 * @LastEditors: 郁南
 * @Date: 2021-12-31 08:30:40
 * @LastEditTime: 2021-12-31 08:35:56
 * @FilePath: /vue-component-demo/components/lib/demo/src/main.vue
 * @Description: 
-->
<template>
  <div class="m-demo">
    这是一个安装的组件Demo 哈哈哈
  </div>
</template>

<script>
export default {
  name: "Demo",
};
</script>

<style>
.m-demo {
  color: aqua;
}
</style>

// webpack/src/index.tsx
/*
 * @Author: 郁南
 * @LastEditors: 郁南
 * @Date: 2021-11-05 08:39:21
 * @LastEditTime: 2021-11-06 19:48:50
 * @FilePath: \webpack\src\index.tsx
 * @Description:
 */

import ReactDOM from 'react-dom'
import App from './App'
import './index.less'

ReactDOM.render(<App />, document.getElementById('root'))
